# Render.com deployment configuration for frontend
services:
  - type: web
    name: ai-flashcards-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-flashcards-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
