# Render.com deployment configuration for Rails backend
services:
  # Rails API service
  - type: web
    name: ai-flashcards-api
    env: ruby
    buildCommand: bundle install && bundle exec rails db:migrate && bundle exec rails db:seed
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-flashcards-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production

  # PostgreSQL database
  - type: pserv
    name: ai-flashcards-db
    env: docker
    dockerfilePath: ./Dockerfile.postgres
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
